name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # Node.js와 Yarn 설정
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.10.0' # Node.js 버전 설정
          cache: 'yarn'

      # 의존성 설치 (frozen-lockfile)
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # Lint 실행
      - name: Run Lint
        run: yarn lint

      # 테스트 실행
      - name: Run Tests
        run: yarn test

      # 프로젝트 빌드
      - name: Build the project
        run: yarn build

      # Chromatic으로 Storybook 실행
      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          # ⚠️ Make sure to configure a `CHROMATIC_PROJECT_TOKEN` repository secret
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}

      # Firebase에 배포
      - name: Deploy to Firebase
        run: firebase deploy
