name: CI/CD Pipeline with Firebase Deploy and Chromatic

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # PR에 대한 빌드 및 Firebase 배포
  build_and_preview:
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      # 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Node.js와 Yarn 설정
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.10.0'
          cache: 'yarn'

      # 의존성 설치 (frozen-lockfile)
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # Lint 실행
      - name: Run Lint
        run: yarn lint

      # 테스트 실행
      - name: Run Tests
        run: yarn test

      # 빌드 실행
      - name: Build the project
        run: yarn build

      # Firebase PR Preview 배포
      - name: Firebase Deploy Preview
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_RELAX_TOGETHER }}
          projectId: relax-together

  # main 브랜치로 머지될 때 Firebase 배포
  build_and_deploy:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      # 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Node.js와 Yarn 설정
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.10.0'
          cache: 'yarn'

      # 의존성 설치 (frozen-lockfile)
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # Lint 실행
      - name: Run Lint
        run: yarn lint

      # 테스트 실행
      - name: Run Tests
        run: yarn test

      # 빌드 실행
      - name: Build the project
        run: yarn build

      # Firebase 라이브 배포
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_RELAX_TOGETHER }}
          channelId: live
          projectId: relax-together

  # Chromatic 실행 (스토리북 배포)
  run_chromatic:
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      # 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Node.js와 Yarn 설정
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.10.0'
          cache: 'yarn'

      # 의존성 설치 (frozen-lockfile)
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # Chromatic 실행
      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
